using System.Collections.Generic;

namespace JGeneral.IO.GPIO
{
    public static class Pins
    {
        public enum Datasheet
        {
            P3V3_0 = 1,
            P3V3_1 = 17,
            P5V_0 = 2,
            P5V_1 = 4,
            GROUND_0 = 6,
            GROUND_1 = 9,
            GROUND_2 = 14,
            GROUND_3 = 20,
            GROUND_4 = 25,
            GROUND_5 = 30,
            GROUND_6 = 34,
            GROUND_7 = 39,
            GPIO_0 = 27,
            ID_SD = GPIO_0,
            GPIO_1 = 28,
            ID_SC = GPIO_1,
            GPIO_2 = 3,
            SDA = GPIO_2,
            GPIO_3 = 5,
            SCL = GPIO_3,
            GPIO_4 = 7,
            GPCLK0 = GPIO_4,
            GPIO_5 = 29,
            GPIO_6 = 31,
            GPIO_7 = 26,
            CE1 = GPIO_7,
            GPIO_8 = 24,
            CE0 = GPIO_8,
            GPIO_9 = 21,
            MISO = GPIO_9,
            GPIO_10 = 19,
            MOSI = GPIO_10,
            GPIO_11 = 23,
            SCLK = GPIO_11,
            GPIO_12 = 32,
            PWM0 = GPIO_12,
            GPIO_13 = 33,
            PWM1 = GPIO_13,
            GPIO_14 = 8,
            TXD = GPIO_14,
            GPIO_15 = 10,
            RXD = GPIO_15,
            GPIO_16 = 36,
            GPIO_17 = 11,
            GPIO_18 = 12,
            PCM_CLK = GPIO_18,
            GPIO_19 = 35,
            PCM_FS = GPIO_19,
            GPIO_20 = 38,
            PCM_DIN = GPIO_20,
            GPIO_21 = 40,
            PCM_DOUT = GPIO_21,
            GPIO_22 = 15,
            GPIO_23 = 16,
            GPIO_24 = 18,
            GPIO_25 = 22,
            GPIO_26 = 37,
        }
    }
}